[
  {
    "group": {
      "enabled": true,
      "name": "dollar"
    }
  },
  {
    "group": {
      "enabled": true,
      "name": "generalise"
    }
  },
  {
    "ignore": {
      "name": "Avoid lambda"
    }
  },
  {
    "ignore": {
      "name": "Redundant lambda"
    }
  },
  {
    "ignore": {
      "name": "Use lambda-case"
    }
  },
  {
    "ignore": {
      "name": "Use tuple-section"
    }
  }
]
