trigger:
  - master

pool:
  vmImage: Ubuntu-16.04

steps:

  - script: |
      mkdir --parents $HOME/.local/bin
      export PATH=$HOME/.local/bin:$PATH
      mkdir --parents /tmp/stack
      pushd /tmp/stack
      curl --location --output stack.tar.gz 'https://github.com/commercialhaskell/stack/releases/download/v1.9.3/stack-1.9.3-linux-x86_64.tar.gz'
      gunzip stack.tar.gz
      tar --extract --file stack.tar --strip-components 1
      mv stack $HOME/.local/bin/
      popd
      stack --version

  - script: |
      pwd
      ls
      stack setup
