trigger:
  - master

pool:
  vmImage: Ubuntu-16.04

steps:

  - script: |
      cd /tmp
      curl --location --output stack.tar.gz 'https://github.com/commercialhaskell/stack/releases/download/v1.9.3/stack-1.9.3-linux-x86_64.tar.gz'
      gunzip stack.tar.gz
      tar --extract --file stack.tar --strip-components 1
      mv stack /usr/local/bin/
      stack --version
